#!/bin/sh
APPDIR=`dirname $0`;
java  -Dgwt.args="-out www-test" -cp "$APPDIR/src:$APPDIR/test:$APPDIR/bin:/opt/lib/junit/junit-4.4.jar:/opt/lib/gwt/gwt-linux-1.4.61/gwt-user.jar:/opt/lib/gwt/gwt-linux-1.4.61/gwt-dev-linux.jar" junit.textui.TestRunner org.aprestos.webdev.gwtapplications.client.tests.GWTApplicationsTest "$@";
