#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:$APPDIR/bin:/opt/lib/gwt/gwt-linux-1.4.61/gwt-user.jar:/opt/lib/gwt/gwt-linux-1.4.61/gwt-dev-linux.jar" com.google.gwt.i18n.tools.I18NSync -out $APPDIR/src org.aprestos.webdev.gwtapplications.client.GWTApplicationsMessages -createMessages ;

