/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'joaovieg' at '10/09/17 20:41' with Gradle 2.13
 *
 * @author joaovieg, @date 10/09/17 20:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
