
CREATE TABLE DATA_OWNER  (
	ID BIGINT  NOT NULL IDENTITY,
	NAME VARCHAR(30) NOT NULL,
	constraint DATA_OWNER_UN unique (ID),
	CONSTRAINT DATA_OWNER_PK PRIMARY KEY (ID)
) ;

CREATE TABLE DOCUMENT_TYPE  (
	CODE VARCHAR(2) NOT NULL ,
	DESCRIPTION VARCHAR(60) NOT NULL,
	constraint DOCUMENT_TYPE_UN unique (CODE),
	CONSTRAINT DOCUMENT_TYPE_PK PRIMARY KEY (CODE)
) ;
