
. ./VARS.sh

cf ic run --name $CONTAINER --link $KAFKA_CONTAINER:$KAFKA_CONTAINER_ALIAS --link $MONGO_CONTAINER:$MONGO_CONTAINER_ALIAS -m $BX_CONTAINER_MEMORY $BX_IMG

sleep 12
cf ic logs $CONTAINER
