IMG=rrunner
KAFKA_CONTAINER=kafka
KAFKA_CONTAINER_ALIAS=kafka
MONGO_CONTAINER=mongo
MONGO_CONTAINER_ALIAS=mongo
CONTAINER=$IMG
BX_REGISTRY=registry.ng.bluemix.net/mynodeappbue
BX_IMG=$BX_REGISTRY/$IMG
BX_CONTAINER_MEMORY=128

