#%RAML 1.0 Trait
queryParameters:
  q:
    required: true
    description: |
      JSON array [{"field1","value1","operator1"},{"field2","value2","operator2"}
      ,...,{"fieldN","valueN","operatorN"}] <<description>>
    example: |
      <<example>>
responses:
  404:
    description: Search returns no matching results
    body:
      application/json:
        example: !include ../examples/404.json
