#%RAML 1.0
title: items
version: v1
protocols: [ HTTPS ]
baseUri: http://localhost
mediaType: application/json
types:
  Item:   !include types/Item.raml
  Error:  !include types/Error.raml
securitySchemes:
  basicAuth:
    description: Each request must contain the headers necessary for
                 basic authentication
    type: Basic Authentication
    describedBy:
      headers:
        Authorization:
          description: Used to send the Base64-encoded "username:password"
                       credentials
          type: string
      responses:
        401:
          description: |
            Unauthorized. Either the provided username and password
            combination is invalid, or the user is not allowed to access
            the content provided by the requested URL.
/api/v1/items:
  get:
    queryParameters:
      cat?: string
      subcat?: string
    responses:
      200:
        body:
          application/json:
            type: Item[]
            example: !include examples/items.json
      404:
        body:
          application/json:
            type: Error
            example: !include examples/error_notfound.json
  post:
    queryParameters:
      access_token:
        description: "The access token provided by the authentication application"
        example: AABBCCDD
        required: true
        type: string
    body:
      application/json:
        type: Item
        example: !include examples/item_noid.json
    responses:
      201:
        body:
          application/json:
            type: Item
            example: !include examples/item.json
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Item
              example: !include examples/item.json
        404:
          body:
            application/json:
              type: Error
              example: !include examples/error_notfound.json
    put:
      body:
        application/json:
          type: Item
          example: !include examples/item.json
      queryParameters:
        access_token:
          description: "The access token provided by the authentication application"
          example: AABBCCDD
          required: true
          type: string
      responses:
        200:
          body:
            application/json:
              type: Item
              example: !include examples/item.json
        404:
          body:
            application/json:
              type: Error
              example: !include examples/error_notfound.json
    delete:
      queryParameters:
        access_token:
          description: "The access token provided by the authentication application"
          example: AABBCCDD
          required: true
          type: string
      responses:
        204:
        404:
          body:
            application/json:
              type: Error
              example: !include examples/error_notfound.json
