/*
 * Exceptions.h
 *
 *  Created on: Feb 3, 2010
 *      Author: dev
 */

#ifndef EXCEPTIONS_H_
#define EXCEPTIONS_H_

#define BASE_EXCEPTION_NUMBER	3000

#define EX_GET_SOCKET_FAILED			BASE_EXCEPTION_NUMBER + 1
#define EX_CONNECT_FAILED				BASE_EXCEPTION_NUMBER + 2
#define EX_BIND_FAILED					BASE_EXCEPTION_NUMBER + 3
#define EX_LISTEN_CALL_FAILED			BASE_EXCEPTION_NUMBER + 4
#define EX_NO_CONNECTION				BASE_EXCEPTION_NUMBER + 5
#define EX_NO_RESPONSE					BASE_EXCEPTION_NUMBER + 6
#define EX_SEND_FAILED					BASE_EXCEPTION_NUMBER + 7
#define EX_TIMEOUT						BASE_EXCEPTION_NUMBER + 8
#define EX_RECEIVE_FAILED				BASE_EXCEPTION_NUMBER + 9

#endif /* EXCEPTIONS_H_ */
