#%RAML 1.0 DataType
uses:
  Basic: ../library/basicTypes.raml
  Collection: ../library/collectionTypes.raml
example: !include ../examples/relatedClinic.json
type: Collection.RelatedClinic
properties:
  Networks:
    type: Collection.RelatedNetwork[]
    description: Optional list of any networks associated with this clinic
    required: false
  Providers:
    type: Collection.RelatedProvider[]
    description: Optional list of any providers associated with this clinic
    required: false
