#%RAML 1.0 DataType
uses:
  Basic: ../library/basicTypes.raml
type: object
example: !include ../examples/providerMedicaid.json
properties:
  Number:
    type: string
    description: |
      Uniquely identifies a specific provider within the state's Medicaid program.
  State:
    description: The issuing US State for the medicaid license.
    type: Basic.State
