#%RAML 1.0 DataType
uses:
  Basic: ../library/basicTypes.raml
  Collection: ../library/collectionTypes.raml

type: Collection.RelatedNetwork
properties:
  Clinics:
    type: Collection.RelatedClinic[]
    description: Optional list of any clinics associated with this network
    required: false
  Providers:
    type: Collection.RelatedProvider[]
    description: Optional list of any providers associated with this network
    required: false
