#%RAML 1.0 DataType
uses:
  Basic: ../library/basicTypes.raml
  Collection: ../library/collectionTypes.raml
example: !include ../examples/networkProviderRelationship.json
type: object
properties:
  Name:
    type: string
    description: The provider's name.
  Link:
    type: Basic.Link
    description: Hyperlink to entity details and any other related sub-entites.
    required: true
  Clinics: Collection.RelatedClinic[]
