#%RAML 1.0 DataType
uses:
  Basic: ../library/basicTypes.raml

description: represents the postal address for a physical location such as a
  clinic or a business.
example: !include ../examples/newAddress.json
type: object
properties:
  Type:
    enum: [D, G, M, B, P]
    description: |
      D', 'G', 'M', 'B', 'P' for 'Directory', 'GeoCoding', 'Mailing',
      'Billing'  and 'Payment'
  Line1: string
  Line2:
    type: string
    required: false
  Line3:
    type: string
    required: false
  City:
    type: string
    required: false
  State:
    type: Basic.State
    required: false
  ZIPCode:
    type: Basic.ZIP
    required: false
  County:
    type: string
    required: false
  Country:
    type: Basic.Country
    required: false
    default: USA
  Province:
    type: string
    required: false
  Latitude:
    type: number
    required: false
  Longitude:
    type: number
    required: false
