#%RAML 1.0 DataType
uses:
  Basic: ../library/basicTypes.raml
  Collection: ../library/collectionTypes.raml

example: !include ../examples/newClinicProvider.json
type: Collection.NewClinicRelationship | Collection.NewProviderRelationship
description: represents a relationship for a provider to a clinic
properties:
  Hours:
    type: Basic.OpeningHours[]
    minItems: 1
    maxItems: 7
    description: The hours for which this clinic operates for this relationship.
    required: false
  Comments:
    type: string
    required: false
  ClearLicenseNumber:
    type: boolean
    required: false
    default: false
  ProviderSpecialistClinic:
    type: boolean
    required: false
    default: false
  ProviderRelationship:
    enum: [A, O, P]
    description: A means Associate, O means Owner and P means Partner.
    required: false
    #default: "A"
  PayClinicOrProvider:
    enum: [P, C]
    description: |
      P means make the payment to the provider directly, C the default, means
      to pay the clinic instead.
    required: false
    default: "C"
  DeltaPrecertified:
    type: boolean
    required: false
    default: false
  CorporatePayment:
    type: boolean
    required: false
    default: false
  WitholdPayments:
    type: boolean
    required: false
    default: false
  ProviderCOB:
    type: boolean
    required: false
    default: false
  BCI:
    type: object
    required: false
    properties:
      Billed:
        type: string
        required: true
      Id:
        type: string
        required: true
  ProviderClaimInReview:
    type: boolean
    required: false
    default: false
  ProfessionalReviewUnderway:
    type: boolean
    required: false
    default: false
