#%RAML 1.0 DataType
uses:
  Basic: ../library/basicTypes.raml
type: object
example: !include ../examples/newCarrier.json
properties:
  ClearCarrierNo:
    type: integer
    description: Uniquely identifies the carrier within the "Clear" system.
    required: true
  Description:
    type: string:
    description: A descriptive name for the carrier.
    required: true
  Effective: Basic.EffectivePeriod
  ContactName:
    type: string
    description: The name of a contact person for the carrier.
    required: false
  Manager:
    type: string
    description: The name of the person managing this account
    required: false
  Comments:
    type: string
    description: Any useful comments on the carrier.
    required: false
