#%RAML 1.0 DataType
uses:
  Basic: ../library/basicTypes.raml

type: object
example: !include ../examples/newFocusReview.json
properties:
  AuditNumber:
    type: integer
    example: 9999
  ProcedureCodes:
    type: object
    required: false
    properties:
      RangeStart:
        type: string
        example: "00120"
      RangeEnd:
        type: string
        example: "00140"
  Commenced: date-only
  Terminated:
    type: date-only
    required: false
  Reason:
    type: string
    required: false
    example: "Arbitrary"
  Comments:
    type: string
    required: false
    example: "Blah blah blah"
  Links: Basic.Link[]
