#%RAML 1.0 DataType
uses:
  Basic: ../library/basicTypes.raml

example: !include ../examples/newLegalAddress.json
type: object
properties:
  Id:
    type: integer
    required: false
  Line1: string
  Line2:
    type: string
    required: false
  Line3:
    type: string
    required: false
  City:
    type: string
    required: false
  State:
    type: Basic.State
    required: false
  ZIPCode:
    type: Basic.ZIP
    required: false
  Effective: Basic.EffectivePeriod
