#%RAML 1.0 DataType
uses:
  Basic: ../library/basicTypes.raml
  Collection: ../library/collectionTypes.raml
example: !include ../examples/newNetworkProviderRelationship.json
type: object
properties:
  Provider:
    type: object
    properties:
      Id: integer
      Clinics: Collection.NewNetworkClinicRelationship[]
