#%RAML 1.0 DataType
uses:
  Basic: ../library/basicTypes.raml
  Collection: ../library/collectionTypes.raml

example: !include ../examples/newProviderCredentials.json
type: object
properties:
  Credentialed:	date-only
  LicenseSuspended:
    type: boolean
    required: false
    default: false
  LicenseSuspendedComments:
    type: string
    required: false
  DiscplinaryAction:
    type: boolean
    required: false
    default: false
  DiscplinaryActionComments:
    type: string
    required: false
  HealthProblem:
    type: boolean
    required: false
    default: false
  HealthProblemComments:
    type: string
    required: false
  FelonyMisdemeanor:
    type: boolean
    required: false
    default: false
  FelonyMisdemeanorComments:
    type: string
    required: false
  MalpracticeExper:
    type: boolean
    required: false
    default: false
  MalpracticeExperComments:
    type: string
    required: false
  DEARestricted:
    type: boolean
    required: false
    default: false
  DEARestrictedComments:
    type: string
    required: false
  CredentialingLevel:
    enum: [Custom, FFS, NCQA, Secondary, Special]
    required: false
