#%RAML 1.0 DataType
uses:
  Basic: ../library/basicTypes.raml

type: object
example: !include ../examples/updateableDisciplinaryAction.json
properties:
  OriginatorCode:
    enum: [ BOARD, DELTA ]
    description: Category code used to indicate the origin of the disciplary action.
    required: false
  Description:
    type: string
    description: A text description of the disciplnary action.
    required: false
    example: "Administrative Suspension"
  Comments:
    type: string
    description: Any comments related to the incident.
    required: false
    example: "Reinstated 2008-12-12"
  Effective:
    type: Basic.EffectivePeriod
    required: false
