#%RAML 1.0 DataType
uses:
  Basic: ../library/basicTypes.raml
  Collection: ../library/collectionTypes.raml

example: !include ../examples/updateableClinicCredentials.json
type: object
properties:
  Credentialed:
    type: date-only
    required: false
  HandicapAccess:
    type: boolean
    required: false
  CPRTrained:
    type: boolean
    required: false
  EmergencyTrained:
    type: boolean
    required: false
  EmergencyKit:
    type: boolean
    required: false
  PublicTransport:
    type: boolean
    required: false
  HandicappedParking:
    type: boolean
    required: false
  CDCAndOSHARulesCompliance:
    type: boolean
    required: false
  DeptHealthRulesCompliance:
    type: boolean
    required: false
