#%RAML 1.0 DataType
uses:
  Basic: ../library/basicTypes.raml

type: object
example: !include ../examples/updateableFocusReview.json
properties:
  AuditNumber:
    type: integer
    example: 9999
    required: false
  ProcedureCodes:
    type: object
    required: false
    properties:
      RangeStart:
        type: string
        example: "00120"
        required: false
      RangeEnd:
        type: string
        example: "00140"
        required: false
  Commenced:
    type: date-only
    required: false
  Terminated:
    type: date-only
    required: false
  Reason:
    type: string
    required: false
    example: "Arbitrary"
  Comments:
    type: string
    required: false
    example: "Blah blah blah"
  Links:
    type: Basic.Link[]
    required: false
